// LLM Prompt Templates for Sector Customization
// Generated on 2025-07-19T15:38:45.070Z

export const llmPrompts = {
  "generatedAt": "2025-07-19T15:38:45.070Z",
  "instructions": "These prompts help LLMs customize websites for specific sectors",
  "sectors": {
    "industrial_machinery": {
      "sectorName": "Industrial Machinery & Equipment",
      "customizationPrompt": "You are customizing a website for a Industrial Machinery & Equipment company in India. \n\nKey Focus Areas:\n- Target Audience: B2B + Industrial\n- Market Position: Premium technology provider\n- Tone: Professional, technical, authoritative\n\nCustomization Guidelines:\n1. Update company information with sector-specific details\n2. Use blue color scheme for professional appearance\n3. Focus on 3 main product categories\n4. Highlight 6 key services\n5. Emphasize certifications: ISO 9001:2015, CE Marking, BIS Standards, Make in India\n\nIndian Market Considerations:\n- Include Indian Rupee pricing\n- Mention Indian standards and certifications\n- Use locally relevant examples\n- Consider both English and regional language support",
      "contentPrompt": "Create compelling content for a Industrial Machinery & Equipment website targeting Indian businesses/consumers.\n\nContent Requirements:\n- Hero section with industry-specific messaging\n- Product descriptions emphasizing quality and value\n- Service information with local context\n- Testimonials from Indian clients\n- Contact information with Indian phone numbers and addresses\n\nKey Messages to Include:\n- Deep understanding of Indian manufacturing needs with global technology standards\n- Quality standards and certifications\n- Local service and support\n- Competitive pricing for Indian market",
      "imagePrompt": "Select images for a Industrial Machinery & Equipment website with these characteristics:\n\nVisual Style: professional, clean, technical\nPrimary Subjects: factory, machinery, industrial environment\nSecondary Elements: workers, precision, modern equipment\n\nImage Categories Needed:\n- Hero background: Modern factory, machinery, industrial environment\n- Product images: High-quality workers, precision, modern equipment\n- Company photos: Professional Indian workplace\n- Team photos: Diverse Indian professionals\n- Facility images: Clean, modern factory, machinery, industrial environment\n\nBrand Colors: blue theme\nEnsure all images reflect Indian context and professionalism."
    },
    "electronics_electrical": {
      "sectorName": "Electronics & Electrical Goods",
      "customizationPrompt": "You are customizing a website for a Electronics & Electrical Goods company in India. \n\nKey Focus Areas:\n- Target Audience: B2B + Professional\n- Market Position: Innovation leader\n- Tone: Modern, innovative, reliable\n\nCustomization Guidelines:\n1. Update company information with sector-specific details\n2. Use purple color scheme for professional appearance\n3. Focus on 4 main product categories\n4. Highlight 6 key services\n5. Emphasize certifications: BIS Certification, RoHS Compliance, FCC Approved, CE Marking, ISO 9001:2015\n\nIndian Market Considerations:\n- Include Indian Rupee pricing\n- Mention Indian standards and certifications\n- Use locally relevant examples\n- Consider both English and regional language support",
      "contentPrompt": "Create compelling content for a Electronics & Electrical Goods website targeting Indian businesses/consumers.\n\nContent Requirements:\n- Hero section with industry-specific messaging\n- Product descriptions emphasizing quality and value\n- Service information with local context\n- Testimonials from Indian clients\n- Contact information with Indian phone numbers and addresses\n\nKey Messages to Include:\n- Combining international technology with local market expertise and support\n- Quality standards and certifications\n- Local service and support\n- Competitive pricing for Indian market",
      "imagePrompt": "Select images for a Electronics & Electrical Goods website with these characteristics:\n\nVisual Style: sleek, modern, high-tech\nPrimary Subjects: innovation, digital, modern\nSecondary Elements: efficiency, smart solutions, future\n\nImage Categories Needed:\n- Hero background: Modern innovation, digital, modern\n- Product images: High-quality efficiency, smart solutions, future\n- Company photos: Professional Indian workplace\n- Team photos: Diverse Indian professionals\n- Facility images: Clean, modern innovation, digital, modern\n\nBrand Colors: purple theme\nEnsure all images reflect Indian context and professionalism."
    },
    "textiles_garments": {
      "sectorName": "Textiles and Garments",
      "customizationPrompt": "You are customizing a website for a Textiles and Garments company in India. \n\nKey Focus Areas:\n- Target Audience: B2B + Export\n- Market Position: Heritage with modern excellence\n- Tone: Elegant, traditional, quality-focused\n\nCustomization Guidelines:\n1. Update company information with sector-specific details\n2. Use orange color scheme for professional appearance\n3. Focus on 3 main product categories\n4. Highlight 6 key services\n5. Emphasize certifications: GOTS Certified, OEKO-TEX Standard, WRAP Certification, BCI Member, ISO 9001:2015\n\nIndian Market Considerations:\n- Include Indian Rupee pricing\n- Mention Indian standards and certifications\n- Use locally relevant examples\n- Consider both English and regional language support",
      "contentPrompt": "Create compelling content for a Textiles and Garments website targeting Indian businesses/consumers.\n\nContent Requirements:\n- Hero section with industry-specific messaging\n- Product descriptions emphasizing quality and value\n- Service information with local context\n- Testimonials from Indian clients\n- Contact information with Indian phone numbers and addresses\n\nKey Messages to Include:\n- Perfect blend of traditional Indian craftsmanship with modern manufacturing excellence\n- Quality standards and certifications\n- Local service and support\n- Competitive pricing for Indian market",
      "imagePrompt": "Select images for a Textiles and Garments website with these characteristics:\n\nVisual Style: classic, elegant, timeless\nPrimary Subjects: heritage, craftsmanship, authenticity\nSecondary Elements: tradition, quality, artisan\n\nImage Categories Needed:\n- Hero background: Modern heritage, craftsmanship, authenticity\n- Product images: High-quality tradition, quality, artisan\n- Company photos: Professional Indian workplace\n- Team photos: Diverse Indian professionals\n- Facility images: Clean, modern heritage, craftsmanship, authenticity\n\nBrand Colors: orange theme\nEnsure all images reflect Indian context and professionalism."
    },
    "agriculture_agro": {
      "sectorName": "Agriculture & Agro Products",
      "customizationPrompt": "You are customizing a website for a Agriculture & Agro Products company in India. \n\nKey Focus Areas:\n- Target Audience: B2B + Professional\n- Market Position: Sustainable solutions provider\n- Tone: Supportive, sustainable, progressive\n\nCustomization Guidelines:\n1. Update company information with sector-specific details\n2. Use green color scheme for professional appearance\n3. Focus on 3 main product categories\n4. Highlight 6 key services\n5. Emphasize certifications: Organic India Certified, FSSAI Licensed, APEDA Registered, ISO 22000, Global GAP\n\nIndian Market Considerations:\n- Include Indian Rupee pricing\n- Mention Indian standards and certifications\n- Use locally relevant examples\n- Consider both English and regional language support",
      "contentPrompt": "Create compelling content for a Agriculture & Agro Products website targeting Indian businesses/consumers.\n\nContent Requirements:\n- Hero section with industry-specific messaging\n- Product descriptions emphasizing quality and value\n- Service information with local context\n- Testimonials from Indian clients\n- Contact information with Indian phone numbers and addresses\n\nKey Messages to Include:\n- Comprehensive agricultural solutions from farm to fork with sustainability focus\n- Quality standards and certifications\n- Local service and support\n- Competitive pricing for Indian market",
      "imagePrompt": "Select images for a Agriculture & Agro Products website with these characteristics:\n\nVisual Style: sleek, modern, high-tech\nPrimary Subjects: innovation, digital, modern\nSecondary Elements: efficiency, smart solutions, future\n\nImage Categories Needed:\n- Hero background: Modern innovation, digital, modern\n- Product images: High-quality efficiency, smart solutions, future\n- Company photos: Professional Indian workplace\n- Team photos: Diverse Indian professionals\n- Facility images: Clean, modern innovation, digital, modern\n\nBrand Colors: green theme\nEnsure all images reflect Indian context and professionalism."
    },
    "chemicals_pharmaceuticals": {
      "sectorName": "Chemicals and Pharmaceuticals",
      "customizationPrompt": "You are customizing a website for a Chemicals and Pharmaceuticals company in India. \n\nKey Focus Areas:\n- Target Audience: B2B + Professional\n- Market Position: Quality and compliance leader\n- Tone: Scientific, precise, trustworthy\n\nCustomization Guidelines:\n1. Update company information with sector-specific details\n2. Use blue color scheme for professional appearance\n3. Focus on 3 main product categories\n4. Highlight 6 key services\n5. Emphasize certifications: WHO-GMP, US FDA, EU GMP, ISO 9001:2015, NABL Accredited, DSIR Recognized\n\nIndian Market Considerations:\n- Include Indian Rupee pricing\n- Mention Indian standards and certifications\n- Use locally relevant examples\n- Consider both English and regional language support",
      "contentPrompt": "Create compelling content for a Chemicals and Pharmaceuticals website targeting Indian businesses/consumers.\n\nContent Requirements:\n- Hero section with industry-specific messaging\n- Product descriptions emphasizing quality and value\n- Service information with local context\n- Testimonials from Indian clients\n- Contact information with Indian phone numbers and addresses\n\nKey Messages to Include:\n- World-class quality systems meeting global regulatory standards\n- Quality standards and certifications\n- Local service and support\n- Competitive pricing for Indian market",
      "imagePrompt": "Select images for a Chemicals and Pharmaceuticals website with these characteristics:\n\nVisual Style: professional, clean, technical\nPrimary Subjects: factory, machinery, industrial environment\nSecondary Elements: workers, precision, modern equipment\n\nImage Categories Needed:\n- Hero background: Modern factory, machinery, industrial environment\n- Product images: High-quality workers, precision, modern equipment\n- Company photos: Professional Indian workplace\n- Team photos: Diverse Indian professionals\n- Facility images: Clean, modern factory, machinery, industrial environment\n\nBrand Colors: blue theme\nEnsure all images reflect Indian context and professionalism."
    },
    "consumer_goods": {
      "sectorName": "Consumer Goods and Household Products",
      "customizationPrompt": "You are customizing a website for a Consumer Goods and Household Products company in India. \n\nKey Focus Areas:\n- Target Audience: B2C + Retail\n- Market Position: Value and convenience champion\n- Tone: Friendly, accessible, value-oriented\n\nCustomization Guidelines:\n1. Update company information with sector-specific details\n2. Use pink color scheme for professional appearance\n3. Focus on 3 main product categories\n4. Highlight 6 key services\n5. Emphasize certifications: ISI Mark, BIS Standards, FSSAI Licensed, ISO 9001:2015, Eco-Mark Certified\n\nIndian Market Considerations:\n- Include Indian Rupee pricing\n- Mention Indian standards and certifications\n- Use locally relevant examples\n- Consider both English and regional language support",
      "contentPrompt": "Create compelling content for a Consumer Goods and Household Products website targeting Indian businesses/consumers.\n\nContent Requirements:\n- Hero section with industry-specific messaging\n- Product descriptions emphasizing quality and value\n- Service information with local context\n- Testimonials from Indian clients\n- Contact information with Indian phone numbers and addresses\n\nKey Messages to Include:\n- Products designed specifically for Indian households with unmatched value\n- Quality standards and certifications\n- Local service and support\n- Competitive pricing for Indian market",
      "imagePrompt": "Select images for a Consumer Goods and Household Products website with these characteristics:\n\nVisual Style: warm, inviting, accessible\nPrimary Subjects: home, family, lifestyle\nSecondary Elements: comfort, convenience, quality\n\nImage Categories Needed:\n- Hero background: Modern home, family, lifestyle\n- Product images: High-quality comfort, convenience, quality\n- Company photos: Professional Indian workplace\n- Team photos: Diverse Indian professionals\n- Facility images: Clean, modern home, family, lifestyle\n\nBrand Colors: pink theme\nEnsure all images reflect Indian context and professionalism."
    },
    "construction_hardware": {
      "sectorName": "Construction Materials and Hardware",
      "customizationPrompt": "You are customizing a website for a Construction Materials and Hardware company in India. \n\nKey Focus Areas:\n- Target Audience: B2B + Professional\n- Market Position: Strength and reliability partner\n- Tone: Strong, dependable, professional\n\nCustomization Guidelines:\n1. Update company information with sector-specific details\n2. Use red color scheme for professional appearance\n3. Focus on 3 main product categories\n4. Highlight 6 key services\n5. Emphasize certifications: BIS Standards, ISI Mark, ISO 9001:2015, Environment Clearance, Quality Assured\n\nIndian Market Considerations:\n- Include Indian Rupee pricing\n- Mention Indian standards and certifications\n- Use locally relevant examples\n- Consider both English and regional language support",
      "contentPrompt": "Create compelling content for a Construction Materials and Hardware website targeting Indian businesses/consumers.\n\nContent Requirements:\n- Hero section with industry-specific messaging\n- Product descriptions emphasizing quality and value\n- Service information with local context\n- Testimonials from Indian clients\n- Contact information with Indian phone numbers and addresses\n\nKey Messages to Include:\n- Trusted partner for India's infrastructure development with proven reliability\n- Quality standards and certifications\n- Local service and support\n- Competitive pricing for Indian market",
      "imagePrompt": "Select images for a Construction Materials and Hardware website with these characteristics:\n\nVisual Style: professional, clean, technical\nPrimary Subjects: factory, machinery, industrial environment\nSecondary Elements: workers, precision, modern equipment\n\nImage Categories Needed:\n- Hero background: Modern factory, machinery, industrial environment\n- Product images: High-quality workers, precision, modern equipment\n- Company photos: Professional Indian workplace\n- Team photos: Diverse Indian professionals\n- Facility images: Clean, modern factory, machinery, industrial environment\n\nBrand Colors: red theme\nEnsure all images reflect Indian context and professionalism."
    }
  }
};